version: '3.5'

services:

  # https://neo4j.com/blog/jetbrains-ide-plugin-graph-database/
  # http://localhost:7474/browser/
  # neo4j / test
  workbook-neo4j:
    image: neo4j:3.5.3
    container_name: workbook-neo4j-srv
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    networks:
      - workbook_network
    environment:
      NEO4J_AUTH: "neo4j/test"


  # http://localhost:8000
  # admin / qwerty
  workbook-interactor:
    image: graphileon/interactor-community
    container_name: workbook-interactor-srv
    volumes:
      - workbook_interactor_data:/persistent/
    ports:
      - 8000:80
    networks:
      - workbook_network

networks:
  workbook_network:
    name: workbook_network

# docker volume rm workbook_interactor_data
volumes:
  workbook_interactor_data:
    name: workbook_interactor_data