version: '3.5'

services:

  # http://localhost:7200/
  workbook-graphdb:
#    image: ontotext/graphdb:8.10.1-se
    image: dhlabbasel/graphdb-free
    container_name: workbook-graphdb-srv
    ports:
      - 7200:7200
    volumes:
      - ./graphdb:/opt/graphdb/home
    networks:
      - workbook_network

networks:
  workbook_network:
    name: workbook_network