version: '3.5'

# Red more: https://github.com/bitnami/bitnami-docker-consul
services:

  # http://localhost:8500/ui/dc1/services
  workbook-consul:
    image: bitnami/consul:1.5.2-ol-7-r11
    container_name: workbook-consul-srv
    restart: always
    #environment:
    #  - CONSUL_BOOTSTRAP_EXPECT=3
    #  - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
    #  - CONSUL_DISABLE_KEYRING_FILE=true
    #  - CONSUL_RETRY_JOIN=consul-node1
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - workbook_consul_data:/bitnami
    networks:
      - workbook-network

networks:
  workbook-network:
    name: workbook-network
    driver: bridge

volumes:
  workbook_consul_data:
    name: workbook_consul_data